### PR TITLE
Add FUNDING.yml

### PR DESCRIPTION
**Pull request by kingthorin**
With custom entry pointing to the foundation donation functionality and github sponsors ORG ref.

(Sets up the "Sponsor ♥" button for this repo.)

### CODE REVIEW

**Comment by kingthorin** [comment]
Ping @EnDe @sslHello :wink:

**Comment by kingthorin** [comment]
Anyone out there??

**Comment by EnDe** [comment]
Sorry for late response.
Unfortunately I as maintainer have no access to the github for OWASP's web page. Access was never granted, even after several complains. Access to the repository here is fine.
Informed @sslHello about this issue to also.

Please be patient ... feel free to ping again. Thanks

**Comment by kingthorin** [comment]
This only impacts this repo and leverages existing functionality on OWASP.org. If your access in this repo is fine just merge it and it’ll work 🙂

**Comment by kingthorin** [comment]
Damnit, sorry looks like I bungled the path somehow. Can’t believe I hadn’t seen that after checking this for merge multiple times. Will get a fix in momentarily. Sorry @EnDe !

**Comment by EnDe** [comment]
<ot>
@kingthorin, do you know if OWASP's website supports other repos than github too? I mean the repo for a project like this, not the repo for OWASP itself.
</ot>

**Comment by kingthorin** [comment]
No the www-project-* repos were setup on purpose to be leveraged as part of some foundation processes.

To get your access sorted out you should be able to create an account [here](https://owasporg.atlassian.net/servicedesk/customer/user/login?destination=portals) (if you don't already have one) and open a ticket.

**Pull request merged**
