### PR TITLE
Fix FUNDING.yml path

### PR DESCRIPTION
**Pull request by kingthorin**
Follow-up to: https://github.com/OWASP/O-Saft/pull/131

image

### CODE REVIEW

**Comment by kingthorin** [comment]
Yay!
image

**Comment by EnDe** [comment]
hmm, after the pull all the dates in https://github.com/OWASP/O-Saft are wrong now.
the comments are ok, and the latest delta of each file is also there, strange, very strange ...

do you have an idea why this happend, yet another git bug?

**Comment by kingthorin** [comment]
That’d be a new one for me. From what I see in the GitHub web ui they all seem okay.

**Comment by EnDe** [comment]
hmm, except your change, all files show last change date months or years ago, I definitely changed files yesterday and today. Can you confirm this?

**Comment by kingthorin** [comment]
Pics;
382E731E-47BA-4525-BF28-AF904EBDCA26
9BC1C607-88EA-47A9-B8FD-5F067AFEA2EE

**Comment by EnDe** [comment]
oops, now some files show "hours ago".
I reloaded the page in the browser several times (avoiding cache) before asking.
All good now. Thanks.

**Comment by kingthorin** [comment]
All good, glad it seems back to normal.

**Pull request merged**
